spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234qwer
    hikari:
      auto-commit: false
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
---
spring:
  profiles:
    active: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop