spring:
  profiles: test

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres&characterEncoding=utf8
    username: postgres
    password: 1234qwer
    hikari:
      auto-commit: false
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:mem:testdb&characterEncoding=utf8
    username: sa
    password: sa

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true